### ISSUE TITLE
Error when trying to fetch specific header.

### ISSUE THREAD

**Issue by rgrinberg** [nojb/ocaml-imap#19]
The relevant snippet from my code looks something like this:

```ocaml
let fields = `Header_fields ["Content-type"] in
let header = `Body_section (`Peek, fields, None) in
run conn (`Cmd (Imap.fetch eset [`Rfc822_text; header]))
```

Which ends up giving me the following error:

```
Decode error: Unexpected string "BODY[HEADER.FIELDS"
```

Am I using this incorrectly?

I'm able to reproduce this on pretty much every gmail message I've tested it against but if you need a concrete example I can do that as well.

**Comment by nojb** [comment]
Looks like a bug.  I'll look into it.

**Comment by nojb** [comment]
I found the bug.  Fix incoming.

**Comment by nojb** [comment]
There is a fix in branch `fix-body-sec-parse`.  Could you pin that, try again and confirm it works ?  Thanks!

**Comment by rgrinberg** [comment]
It works, thanks.

**Comment by rgrinberg** [comment]
@nojb a point release would be great as well please :)

**Comment by nojb** [comment]
Coming up.  Thanks again for reporting!

**Comment by nojb** [comment]
`imap.1.1.1` should be available in `opam` shortly.  Thanks!
