### ISSUE TITLE
Error marking emails as "read"

### ISSUE THREAD

**Issue by rgrinberg** [nojb/ocaml-imap#25]
I get the following error when marking a certain email as read. `<<<` is incoming data from the server while `>>>` is outgoing. Hopefully this is enough for you to diagnose the problem, if not then I can work on creating a reproducible test case.

```
2015-12-02 10:28:53.367877-05:00 Debug <<< * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
* OK [UIDVALIDITY 11] UIDs valid.
* 1863 EXISTS
* 0 RECENT
* OK [UIDNEXT 1899] Predicted next UID.
* OK [HIGHESTMODSEQ 186009]
5 OK [READ-WRITE] [Gmail]/All Mail selected. (Success)

2015-12-02 10:28:53.367949-05:00 Debug >>> 6 UID STORE  FLAGS.SILENT (\Seen)

(((pid 91334) (thread_id 0))
 ((human_readable 2015-12-02T10:28:53-0500)
  (int63_ns_since_epoch 1449070133538730000))
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((src/monitor.ml.Error_
    ((exn
      ("Async_imap.Imap_error(\"BAD: none \\\"Could not parse command\\\"\")"))
     (backtrace
      ("Called from file \"src/deferred0.ml\", line 59, characters 65-68"
       "Called from file \"src/job_queue.ml\", line 164, characters 6-47" ""))
     (monitor
      (((name main) (here ()) (id 1) (has_seen_error true)
        (is_detached false) (kill_index 0))))))
   ((pid 91334) (thread_id 0)))))
```

The mark seen command is being generated using the following code:

```ocaml
  let flags = [`Seen] in
  let cmd = `Cmd (Imap.store_set_flags ~silent:true ~uid:true eset flags) in
```

**Comment by nojb** [comment]
Thanks for the report!

Clearly the problem is that the command that gets sent to the server,
```
2015-12-02 10:28:53.367949-05:00 Debug >>> 6 UID STORE  FLAGS.SILENT (\Seen)
```
is missing a message set specification (between `STORE` and `FLAGS.SILENT`) so the server is complaining.  So either

1) there is a bug in the code that builds the commands (should be trivial to solve)
2) the set `eset` in your code is empty

Probably 1), but I am at work right now so I will have to wait until I get back home to check.

**Comment by rgrinberg** [comment]
It's actually `2)` in my case. Thanks.

Sorry for the silliness.

**Comment by rgrinberg** [comment]
@nojb however, does it make sense for this library to check if the eset is empty and `invalid_arg` if it is perhaps?

Seems like it could help catch errors like this.

**Comment by nojb** [comment]
Absolutely! I am planning to do this tonight.

Out of curiosity: what are you using the library for ?  I am interested to know if it is useful for other people and/or ways to improve it.  Thanks!

**Comment by rgrinberg** [comment]
My use case is pretty simple. Fetch emails from a gmail account according some criteria, process the message/attachments, and mark them as read.

ocaml-imap has been a life saver for this, thanks!

I've only really struggled initially on how to set it up with async/ssl so that's the only thing I'd recommend to improve or document better. I assume most users would want to use this library with lwt and ocaml-tls/ssl

**Comment by nojb** [comment]
Thanks for the info!

I am working in making the api simpler and the implementation more robust and efficient (in particular I got rid of the functions `src` and `dst`).  There is still some work to do, but most of the important changes are in place.  I also added a bare-bones `lwt` client example using the new api.  Check out the [.mli](https://github.com/nojb/ocaml-imap/blob/master/test/imap_lwt.mli) and the corresponding [.ml](https://github.com/nojb/ocaml-imap/blob/master/test/imap_lwt.ml).

Any suggestions, comments or ideas welcome!
