### ISSUE TITLE
Message fetching is quadratic

### ISSUE THREAD

**Issue by d3zd3z** [nojb/ocaml-imap#3]
When fetching more than 10,000 or so messages (or even just flags), the imap lib  demonstrates quadratic behavior.  Profiling suggests that this is at least because of ImapCore.message_data_store using "... @ [att]" to add a new message. This also tends to overwhelm runtime with garbage collection due to the n^2 garbage this generates.

It would also be nice to be able to perform a large fetch (such as return all of the flags in a folder), and be able to display a progress indicator, such as by having the messages passed to a callback, for example.  When using UIDs, because they are sparse, it is difficult to narrow this down to smaller fetches.

BTW, in this case, I've decided to use the Imap library directly, instead of the Lwt interface, because my use is fairly specialized, and a bit different than what typical imap clients would do.

**Comment by nojb** [comment]
Just a quick note that I just did a complete rewrite of the library that should take care of the quadratic behaviour.  It also provides an API that makes it easy to report the progress to the user.  The API is somewhat lower level and the high-level API is gone, though.  Full docs [here](https://nojb.github.io/ocaml-imap).  I am closing this issue for now but feel free to reopen if need to.
